In [2]:
import pandas as pd

In [3]:
import json
import os
os.getcwd()
os.listdir()
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\5A_Traders\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\5A_Traders\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: C:\Users\5A_Traders\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [4]:
contracts = pd.read_pickle("contracts_competition.pkl")

identity0 = pd.read_csv("identity_card_0.tsv", sep="\t")

identity1 = pd.read_csv("identity_card_1.csv")

performance = pd.read_csv("performance.tsv", sep="\t")

medical = pd.read_excel("medical_information.xlsx", skiprows=1)

scouting = pd.read_csv("hockey_scouting_notes.csv")

moms = pd.read_json("moms_notes.json")

In [5]:
dataframes = {
    "contracts": contracts,
    "identity0": identity0,
    "identity1": identity1,
    "medical": medical,
    "performance": performance,
    "scouting": scouting,
    "moms":moms,
}

In [7]:
audit=[]

for name, df in dataframes.items():
    rows=df.shape[0]
    cols=df.shape[1]

    duplicate_rows=df.duplicated().sum()

    total_missing=df.isnull().sum().sum()

    key_cols=[col for col in df.columns if "id" in col.lower()]

    audit.append({
        "file_name": name,
        "rows": rows,
        "columns": cols,
        "duplicate_rows": duplicate_rows,
        "total_missing_values": total_missing,
        "possible_keys": ", ".join(key_cols)

    })

audit_df=pd.DataFrame(audit)
audit_df

,file_name,rows,columns,duplicate_rows,total_missing_values,possible_keys
0,contracts,10000,8,0,513,international_id
1,identity0,888,8,0,0,"numerus_internationalis_ad_identitatem, numeru..."
2,identity1,9112,8,0,222,"international_id, medical_id"
3,medical,10001,11,0,9099,medical_id
4,performance,10000,29,0,1036,international_id
5,scouting,10000,7,0,1837,international_id
6,moms,10000,13,36,3514,

In [11]:
contracts.isnull().sum().sort_values(ascending=False)

number_of_previous_teams    206
contracts_signed            122
captain                      37
salary                       37
jersey_number                37
won_championship             37
draft_year                   37
international_id              0
dtype: int64

In [12]:
identity0.isnull().sum().sort_values(ascending=False)

numerus_internationalis_ad_identitatem    0
numerus_identificationis_ad_medicinam     0
praenomen                                 0
cognomen                                  0
sexus                                     0
aetas_annorum                             0
urbs_natalis                              0
natio                                     0
dtype: int64

In [13]:
identity1.isnull().sum().sort_values(ascending=False)

last_name           37
first_name          37
age                 37
gender              37
birth_city          37
nationality         37
international_id     0
medical_id           0
dtype: int64

In [14]:
performance.isnull().sum().sort_values(ascending=False)

goals                         37
num_of_shots                  37
assists                       37
shot_speed                    37
shot_attempts                 37
low_danger_shots              37
shooting_percentage           37
high_danger_shots             37
medium_danger_shots           37
winning_goals                 37
save_percentage               37
power_play_time               37
power_play_goals              37
penalties_taken               37
time_on_ice                   37
faceoff_win_percentage        37
puck_touches                  37
puck_recoveries               37
puck_possession_time          37
penalty_kill_time             37
penality_minutes              37
passes_attempted              37
time_between_penalties        37
goals_against_total           37
goals_against_average         37
pass_completion_rate          37
passes_completed              37
games_missed_due_to_injury    37
international_id               0
dtype: int64

In [15]:
medical.isnull().sum().sort_values(ascending=False)

medical_information    8519
fitness_level           359
shoe_size                38
return_date              38
sprint_time              38
age_in_years             38
weight                   35
body_fat_percentage      31
medical_id                1
height                    1
physician_signature       1
dtype: int64

In [16]:
scouting.isnull().sum().sort_values(ascending=False)

scout_notes         1038
dominant_hand        651
position              37
years_played          37
experience_level      37
years_pro             37
international_id       0
dtype: int64

In [23]:
moms[moms.duplicated()]

,first_name,last_name,age,birth_city,school_grade,years_in_usa,eye_color,stuffed_animal_name,favourite_board_game,personal_notes,favourite_child_info,favourite_tv_show,favourite_food
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
1306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
1403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
1701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
1906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
2143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
2383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
2822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
2890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
3321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
3557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
3710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
4419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
4642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
4747,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
5274,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
5634,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
6011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
6221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
6693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
6720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
6984,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
7091,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
7299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
7606,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
7630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
7754,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
8250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
8304,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
8377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
8794,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
8922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
9295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,
9773,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"I have no favourite child, I love them all equ...",,